### ISSUE TITLE
Translating URLs

### ISSUE THREAD

**Issue by lchski** [cds-snc/ircc-rescheduler#121]
Hia! Was just quickly looking through the project. I noticed that, while text is translated properly, there are a few instances in which URLs in the French link to English pages.

Two cases in particular:

* [LandingPage.js](https://github.com/cds-snc/ircc-rescheduler/blob/master/web/src/pages/LandingPage.js#L90)
* [RegistrationPage.js](https://github.com/cds-snc/ircc-rescheduler/blob/master/web/src/pages/RegistrationPage.js#L250)

**Comment by pcraig3** [comment]
This is a small part of a larger problem, documented more comprehensively here: https://github.com/cds-snc/ircc-rescheduler/issues/128

Closing this in favour of the other one.
