### ISSUE TITLE
Add "Email" field to forms page

### ISSUE THREAD

**Issue by zakkain** [cds-snc/ircc-rescheduler#127]
![image](https://user-images.githubusercontent.com/546495/40938398-c7cf949a-680f-11e8-8669-805f5511148e.png)

Add an "Email" field to the forms page, so users can supply an email address (unverified, aside from checking if it's a valid email address format) at which they'll receive a confirmation email.

Content:

Label: Email
Description: `We will send a confirmation number to this email address.`
Error state: `You need to provide an email address so we can send you a confirmation message.`

**Comment by emanelfy** [comment]
**Updated description for above the email field:**
`We will send a confirmation message to this email address.`

**Comment by timarney** [comment]
Can someone also note (for tracking) on the confirmation email, which information we're not showing (based on the staff e-mail template) 

- Remove: 
Paper file number + was there any other fields to be removed?

**Comment by timarney** [comment]
Code for this is in the following PR's

https://github.com/cds-snc/ircc-rescheduler/pull/173
https://github.com/cds-snc/ircc-rescheduler/pull/176

**Comment by nmakuch** [comment]
Closing this, Tim has got it merged in (look at previous comment)
