### ISSUE TITLE
Calendar page function: date selection ordering

### ISSUE THREAD

**Issue by emanelfy** [cds-snc/ircc-rescheduler#129]
## Date selection should change from being displayed in order of user selection to chronological order.
This will enable us to remove any unintended hierarchy associated with the date selection order, and present the dates back to the user chronologically for easier comprehension. 
<img width="640" alt="screen shot 2018-06-06 at 2 48 09 pm" src="https://user-images.githubusercontent.com/35348560/41059024-636dfa60-6999-11e8-8560-153a93330d09.png">

**Comment by pcraig3** [comment]
This is in since #146 was merged.
