### ISSUE TITLE
Start page: content / design edits

### ISSUE THREAD

**Issue by emanelfy** [cds-snc/ircc-rescheduler#132]
**Overall Changes:**
- [x] title statement
- [x] bullet points
- [x] warning box
- [x] arrow

<img width="540" alt="screen shot 2018-06-06 at 4 49 19 pm" src="https://user-images.githubusercontent.com/35348560/41064464-98d6e6b6-69a9-11e8-8047-09ddc692f4c7.png">

--

## Title statement
**Content edit:**

> Tell IRCC that you can’t attend your Citizenship test, and request a new appointment.
<img width="719" alt="screen shot 2018-06-06 at 4 51 00 pm" src="https://user-images.githubusercontent.com/35348560/41064541-d273e8ba-69a9-11e8-9e67-e04b85e88e6a.png">

--

## Bullet points
**Content edit:**

> You will need: 
• Your paper file number 
• To describe your reason for rescheduling
<img width="717" alt="screen shot 2018-06-06 at 4 52 08 pm" src="https://user-images.githubusercontent.com/35348560/41064587-fca021c6-69a9-11e8-842e-809c36ea3fb8.png">

--

## Warning box
**Content edit:**

> When you request a new appointment, you will be cancelling your current appointment. It can take up to six weeks to schedule your new appointment.
<img width="719" alt="screen shot 2018-06-06 at 4 53 18 pm" src="https://user-images.githubusercontent.com/35348560/41064637-2874f628-69aa-11e8-9ac7-d64c68d47b06.png">

## Arrow
Should look like this:
<img width="465" alt="screen shot 2018-06-06 at 9 54 53 pm" src="https://user-images.githubusercontent.com/35348560/41074071-43bcbda6-69d4-11e8-9342-4f6547ecc102.png">

**Comment by kyliehavelock** [comment]
Other amendment notes from the [design review](https://docs.google.com/document/d/1tInLMODBMwkK7mXJ0foVr5gvKxuw617_Bw8Dmu50mKw/edit#) include:

- Take the size of the service name way down. It’s already differentiated with a background colour, doesn’t need to be that large as well
- Content problem: “Use this service…” is Grade 15 reading level and complex
Suggest: _Use this service to tell us that you cannot attend your Citizenship test_
- Typographic hierarchy isn’t working here at all. Large, then large and bold, then small? 
Simplify this. Single weight, single size.
- Also, worth standardising the bullets? You will need:
Your paper file number
Your full name
Your reason for rescheduling
- The “(!)” box’s text needs to be simplified and reduced (I know this is a tall order). It reads at a Grade 10 level and is also wordy and repetitive. How about:
_When you request a new appointment, you will be cancelling your current appointment. It may take up to six weeks to schedule your new appointment._
That’s 25 words, not 32, and a Grade 7 level. It removes IRCC (unimportant as to the user, it’s all just the government).
OR:
_Requesting a new appointment cancels your current one. It may take up to six weeks to schedule your new appointment._
That’s 20 words and a Grade 6 level! Zak, weigh in here please.
- Also, that footer – can we tighten it up as well? Put everything on one line – something like:
(Canada wordmark)  |  Privacy | Contact | T&Cs

**Comment by emanelfy** [comment]
All notes from the design review Kylie mentioned above have been included in the issue checklist -- with the exception of one content update Zak will be posting here :)

**Comment by kyliehavelock** [comment]
I might be missing something, I can't see the below items on this issue checklist. Are they in a checklist on another issue @emanelfy ?

- reducing the size of the service name
- switching typography to single weight, single size

**Comment by emanelfy** [comment]
Yup they were listed on this issue (being tackled first) > https://github.com/cds-snc/ircc-rescheduler/issues/130

**Comment by zakkain** [comment]
## Copy addition to address the "no-show" use case

Add below the "Tell IRCC..." title, in plain text:

> If you missed your appointment in the last 30 days, you can still request a new appointment here. If it's been more than 30 days, please [contact IRCC](#) 

That link goes to the Contact page (CSC/webform)

**Comment by nmakuch** [comment]
This issue was closed after merging in [Pull Request #166](https://github.com/cds-snc/ircc-rescheduler/pull/166)
