### ISSUE TITLE
Form page: design edits

### ISSUE THREAD

**Issue by emanelfy** [cds-snc/ircc-rescheduler#133]
**Overall Changes:**
- [x] radio buttons
- [x] guidelines link
- [x] error jumping

--

## Radio buttons
1. Need to increase line-height between the "guidelines" link and the first radio button:
![img_6012](https://user-images.githubusercontent.com/35348560/41065095-86ffd022-69ab-11e8-9292-a97a6bc3c778.jpg)

2. Increase the size of the radio buttons
2a. The buttons should have a 40x40 pixel hit area
![img_6012 2](https://user-images.githubusercontent.com/35348560/41065126-9ff11046-69ab-11e8-9aa4-70a00ba8cded.jpg)

--

## Guidelines link
Link should open up in a new tab, instead of redirecting users away from the tool.
![img_6012 3](https://user-images.githubusercontent.com/35348560/41065216-ec2f55ee-69ab-11e8-828a-026a884e7b47.jpg)

--

## Error jumping
Currently, the page jumps up to the first error a user is required to address.
_**Fix:**_ Users should bounce back to the top of the page where the main error box lives.
![img_6013](https://user-images.githubusercontent.com/35348560/41065423-9a5cb1de-69ac-11e8-9519-f0283e392236.jpg)

**Comment by kyliehavelock** [comment]
We may be removing the link to 'read the guidelines for rescheduling' entirely. See https://trello.com/c/8RMdT5vr/117-read-the-guidelines-link-destination-for-the-rescheduler-tool

**Comment by emanelfy** [comment]
For now we'll keep the link and style accordingly, and remove later in future if necessary.

**Comment by pcraig3** [comment]
The error jumping stuff is fixed since #250 went in. 🎉
