### ISSUE TITLE
Review + confirmation pages: design edits

### ISSUE THREAD

**Issue by emanelfy** [cds-snc/ircc-rescheduler#136]
**Overall changes:**
- [x] text size 
- [x] spacing/margins
- [x] "change" links
- [x] arrow
- [x] contact info

--

## Text size
Reduce size, currently takes up a lot of space.
<img width="346" alt="screen shot 2018-06-06 at 9 59 33 pm" src="https://user-images.githubusercontent.com/35348560/41074215-ed5a96a8-69d4-11e8-8d40-8415a06abec6.png">

--

## Spacing / margins
Increase space between label and user input.
<img width="520" alt="screen shot 2018-06-06 at 10 01 07 pm" src="https://user-images.githubusercontent.com/35348560/41074259-2a9887b4-69d5-11e8-9748-9a553dc0db38.png">

--

## "Change" links
Should be right-aligned, and on the same line as the user input.

--

## Arrow
Change to look like this:
<img width="340" alt="screen shot 2018-06-06 at 10 03 13 pm" src="https://user-images.githubusercontent.com/35348560/41074304-6f6375e8-69d5-11e8-8355-6d3819a2fd00.png">

--

## Contact info
The phone number does not need to be treated visually as a link -- otherwise the email and phone number both look like a single link.
<img width="276" alt="screen shot 2018-06-06 at 10 04 29 pm" src="https://user-images.githubusercontent.com/35348560/41074327-9dcc8e1a-69d5-11e8-9035-b232703acd7c.png">

**Comment by kyliehavelock** [comment]
What text size is proposed @emanelfy ?

**Comment by emanelfy** [comment]
Reduce from 1.7rem to 1.2rem, matching size on the previous calendar page.

**Comment by nmakuch** [comment]
this was merged in yesterday with the AmendReviewConfirmation branch, closing
