### ISSUE TITLE
Content change: six weeks to nine

### ISSUE THREAD

**Issue by emanelfy** [cds-snc/ircc-rescheduler#137]
Based on calculating the longest possible wait time associated with choosing the date furthest away on the two-month view of the calendar: everywhere there is a mention that it could take up to **"6 weeks" to hear back from IRCC, it needs to change to _9 weeks_.** 

_All of our math behind the scenes also needs to change to reflect this._

**Comment by nmakuch** [comment]
This was merged in last Wednesday before usability testing
