### ISSUE TITLE
noJS Calendar: design update

### ISSUE THREAD

**Issue by emanelfy** [cds-snc/ircc-rescheduler#178]
Alternative interface for picking dates that doesn't require javascript.
<img width="360" alt="screen shot 2018-06-25 at 2 05 03 pm" src="https://user-images.githubusercontent.com/35348560/41867498-4d6cc57e-7881-11e8-9626-e8a9d8c955d3.png">

On mobile, will stack:
<img width="346" alt="screen shot 2018-06-25 at 2 09 50 pm" src="https://user-images.githubusercontent.com/35348560/41867566-759846fe-7881-11e8-9bf5-31a65ff9c1cd.png">

**Comment by emanelfy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [No JS: users can pick dates [M]](https://trello.com/c/kJN1BpSY/137-no-js-users-can-pick-dates)

**Comment by emanelfy** [comment]
Updated mocks have been added above to reflect latest design changes @nmakuch @pcraig3 @zakkain

**Comment by pcraig3** [comment]
Closing stuff ever since https://github.com/cds-snc/ircc-rescheduler/pull/222 was merged.
