### ISSUE TITLE
Site-wide design changes

### ISSUE THREAD

**Issue by emanelfy** [cds-snc/ircc-rescheduler#186]
**Overall Changes:**
- [x] typeface
- [x] background colour
- [x] FIP/header
- [x] footer
- [x] link colour
- [x] warning boxes

--

### Typeface
Changing to Source Sans Pro (https://fonts.google.com/specimen/Source+Sans+Pro), only using bold and roman weight.

--

### Background colour
Changing to white across the whole service.

--

### FIP/header
Should now look like this:
<img width="1079" alt="screen shot 2018-06-25 at 2 14 31 pm" src="https://user-images.githubusercontent.com/35348560/41867800-1df28454-7882-11e8-9296-d917a41778e5.png">
1. BETA tag width should be the same as the flag in FIP
2. The text to the right of the BETA tag should be aligned with "Govt. of Canada" in the FIP above
3. Spacing around the BETA tag and above/below the header title "request to resched.." should be equal
4. The only feedback mechanism we're implementing for beta launch will be in the header linked as "_sending your feedback_"

On pages where we don't have the header title "request to resched.." should look like this:
<img width="1076" alt="screen shot 2018-06-25 at 2 21 54 pm" src="https://user-images.githubusercontent.com/35348560/41868135-2ad66c16-7883-11e8-858b-ad32efbf59f1.png">
Those pages include:
1. service confirmation page
2. "something went wrong" page
3. cancel confirmation page

--

### Footer
Logo moves back to the right-side, links in this order:
<img width="1078" alt="screen shot 2018-06-25 at 2 21 27 pm" src="https://user-images.githubusercontent.com/35348560/41868096-12c47370-7883-11e8-90f1-2ceb73ef057f.png">

--

### Link colour
Remove "followed" link state colour (purple) and always display blue link colour for text links.

--

### Warning boxes
Should now look like this:
<img width="629" alt="screen shot 2018-06-25 at 2 36 14 pm" src="https://user-images.githubusercontent.com/35348560/41868803-2a0fe134-7885-11e8-99e4-c5af68aaf074.png">

**Comment by emanelfy** [comment]
@nmakuch Let me know if you have any questions about these changes :)

**Comment by emanelfy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Alpha banner/header redesign.](https://trello.com/c/gT3IHvH5/186-alpha-banner-header-redesign)

**Comment by emanelfy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Explore typography options for the entire service and revisit bolding/headers.](https://trello.com/c/Rqy6Nv2l/187-explore-typography-options-for-the-entire-service-and-revisit-bolding-headers)

**Comment by emanelfy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change the background from grey to white across the whole service.](https://trello.com/c/0VGW3ADA/188-change-the-background-from-grey-to-white-across-the-whole-service)

**Comment by emanelfy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Redesign warning box pattern.](https://trello.com/c/fXMfJbhY/185-redesign-warning-box-pattern)

**Comment by nmakuch** [comment]
This was merged in [PR 216](https://github.com/cds-snc/ircc-rescheduler/pull/216#pullrequestreview-133392578)
