### ISSUE TITLE
Confirmation email updates [design + content]

### ISSUE THREAD

**Issue by zakkain** [cds-snc/ircc-rescheduler#225]
This issue captures design and content updates to the email applicants receive after completing the rescheduling app flow. 

**Current:** 
![image](https://user-images.githubusercontent.com/546495/42236081-ca234498-7ec7-11e8-972c-de60d4ba4101.png)

**Updates:**
- Subject line change: `IRCC confirmation of your request`
- Add a salutation using the `Full name` field: `Hello FULLNAME,`
- Add a line of body text after the salutation, and before the table: `We received your request for a new citizenship appointment. These are the days you selected:`
- Remove the "Full name" table row and only display the "Availability" row
- Add a line of body text below the table: `By September 6, 2018, your local IRCC office will send you a new appointment, or email you to ask for more information.` (same text as on the confirmation page). Is using the dynamic date there possible, @pcraig3 ?

**Comment by anikbrazeau** [comment]
Subject line: IRCC confirmation: you requested a new citizenship appointment / Confirmation d’IRCC : vous avez demandé un nouveau rendez-vous d’examen de citoyenneté


(le français suit)


Hello [FULL NAME],

We received your request for a new citizenship appointment. These are the days you selected:

Availability

By September 6, 2018, your local IRCC office will send you a new appointment, or email you to ask for more information.

--

Bonjour [NOM COMPLET],


Nous avons bien reçu votre demande

Nous avons bien reçu votre demande de nouveau rendez-vous d’examen de citoyenneté. Voici les journées que vous avez sélectionnées : 

Disponibilité

D’ici le 6 septembre 2018, votre bureau local d’IRCC vous enverra les détails de votre nouveau rendez-vous ou communiquera avec vous par courriel pour vous demander des renseignements supplémentaires.

**Comment by emanelfy** [comment]
As a first pass on getting this change live asap, we're going to hold off on dynamic dates and do this for now:

Bolded text: **What's next?**
Below that: `Your local IRCC office will send you a new appointment, or email you to ask for more information.`

Lastly, add contact information (same as confirmation page on service).


--
[@zakkain @anikbrazeau @pcraig3]

**Comment by zakkain** [comment]
French subject line: ``Confirmation d'IRCC de votre demande`

**Comment by anikbrazeau** [comment]
**Subject line:** IRCC confirmation of your request / Confirmation d’IRCC de votre demande

_(le français suit)_

Hello [FULL NAME],

We received your request for a new citizenship appointment. These are the days you selected:

[Availability]

**What's next?**
 
Your local IRCC office will send you a new appointment, or email you to ask for more information.

[Contact] 

--

Bonjour [NOM COMPLET],

Nous avons bien reçu votre demande de nouveau rendez-vous d’examen de citoyenneté. Voici les journées que vous avez sélectionnées :

[Disponibilité]

Quelles sont les étapes suivantes?

Votre bureau local d’IRCC vous enverra les détails de votre nouveau rendez-vous ou communiquera avec vous par courriel pour vous demander des renseignements supplémentaires.

[Contact]
