### ISSUE TITLE
New page: Something went wrong (confirmation emails)

### ISSUE THREAD

**Issue by emanelfy** [cds-snc/ircc-rescheduler#237]
Need messaging for a new "Something went wrong" page in the event that there's a system error and the email notification wasn't sent to staff and/or the user.

Should be along the lines of "something went wrong, please submit your request again" ... 

--
[@zakkain to submit copy for @pcraig3 @timarney]

**Comment by timarney** [comment]
Here's the possible scenarios that I see:

1 - staff email failed
2 - user response email failed
3 - both staff and user email failed

We'll get back a fairly detailed response from Amazon (I have been able to track done a list showing possible errors as of yet)

There's also the possibility that an email failed but Amazon will retry sending X amount of times (I don't think we can handle this case as there's no time limit on this ... user has left the site).

**Comment by zakkain** [comment]
@timarney so, this page would load _after_ the user hits "Send request" on the final page, and would essentially replace the `/confirmation` page that loads when everything works properly. Correct?

**Comment by zakkain** [comment]
Elaborating on that: depending on which case Tim outlined above, we could present this as very different levels of severity. If the staff email failed, absolutely we should ask the user to repeat the process and try again.

But if the user confirmation failed while the staff email _succeeded_, then I would argue we shouldn't ask the user to repeat the process. We shouldn't fire a "Something went wrong" page—we should fire the confirmation page, but with an added piece explaining they won't get a confirmation email (and direct them/include the information to review, so they can write it down).

@emanelfy thoughts?

**Comment by zakkain** [comment]
@emanelfy What do you think of this layout for **Case 1** - only user email fails?

![image](https://user-images.githubusercontent.com/546495/42648081-c4ae2e66-85d3-11e8-985b-450f66fb5d77.png)

obviously a rough mock, I made cutting and pasting screenshots, and not final copy. There's a much better way to handle this layout in design, have any thoughts?

**Comment by emanelfy** [comment]
The error feels too buried on this page, could be missed. 
Needs to go above _"What happens next,"_ reversing the order? @zakkain 

_Please make a copy of your request_ -- also feels vague. Perhaps **"Please make note"** is a more action-oriented way of phrasing that, as in, you're definitely writing this down. (or taking a screenshot or whatever). 
I would also put this on a second line, so it doesn't appear to be such a long sentence and potentially could be missed when skimming.

I think we also need to make it super clear somehow that staff have a copy, it's just that users need to note it on their end. That everything else is okay and going according to plan.
Like: _"not to worry, IRCC staff have received your request, but..."_ along these lines?

**Comment by zakkain** [comment]
Update: After discussing w/ Tim, we have a solution that cuts the number of separate error states and reduces user confusion:

**Case 1 (user email failed)** - point users to a new "confirmation" page. Design and copy on it's way

**Case 2 (staff email failed)** - In this case, we will change the logic so that if the staff email fails the user email will **not send**. We'll direct users to the standard "something went wrong" page. This avoids the confusion of users receiving an email, bu being told to ignore it. This will result in more calls.

**Case 3 (both fail)** - points to the standard "something went wrong" page.

So in effect we only have **1** new error page, not 3., with a bit of smart error handling logic on the back end.

cc @emanelfy @pcraig3 @timarney

**Comment by zakkain** [comment]
### Case 1 (user email failed) confirmation page variant:
![image](https://user-images.githubusercontent.com/546495/42701780-7c94cd5c-8695-11e8-8352-c47774cab9ac.png)

**Changes:**
- removal of the text below the page title reading "We sent you a confirmation email"
- Addition of a "warning" component below the title with the copy: `Sorry, something went wrong. We received your request, but you might not get a confirmation email.  Please make note of your request information:`
- Addition of the dates table from the Review page below the warning , aligned left to the warning text
- 2px #e1e1e1 rule indenting the dates section

cc @timarney @emanelfy

**Comment by timarney** [comment]
Closing this as it's been merged.
