### ISSUE TITLE
Field validation

### ISSUE THREAD

**Issue by timarney** [cds-snc/ircc-rescheduler#238]
We're adding proper field validation to the form inputs:

Theres 2 cases we'll be looking to handle 

1. 2 many characters entered (we'll max at 2000)
2. Invalid Paper File #

These will be in addition of the you haven't entered any data

We'll need to figure out some updated wording to inform the user accordingly (no input vs bad input)

<img width="667" alt="screen shot 2018-07-09 at 11 27 52 am" src="https://user-images.githubusercontent.com/62242/42460311-8888e710-836b-11e8-82a7-84963e4decdf.png">

Note: For the text inputs there will also be HTML 5 validation in place to essentially block the user from entering too many characters.

:: @zakkain @emanelfy

**Comment by pcraig3** [comment]
I put this in the Trello card, but I'll repeat it here for completeness.

Our service can only save 2000 characters (~300 words) so we need to stop people from entering super long explanations or names or whatever.

#### Full name: 
- cannot be empty
- cannot be more than {20 words | 200 characters}

#### Email:
- cannot be empty
- passes email regex + trim whitespace

#### Paper file number:
- cannot be empty
- always contains a letter, followed by 9 numbers (ie, C123456789)

#### Reason:
- cannot be empty
- check as an enum against known values

#### Explanation:
- cannot be empty
- cannot be more than {150 words | 1500 characters}

In addition to all this, we should automatically trim whitespace on all inputs. There is no case in which leading / trailing whitespace is significant that I can think of.

Feel free to weigh in, @emanelfy, @zakkain.

**Comment by pcraig3** [comment]
I put this in the Trello card, but I'll repeat it here for completeness.

Our service can only save 2000 characters (~300 words) so we need to stop people from entering super long explanations or names or whatever.

#### Full name: 
- cannot be empty
- cannot be more than {20 words | 200 characters}

#### Email:
- cannot be empty
- passes email regex + trim whitespace

#### Paper file number:
- cannot be empty
- correctly formatted (_shhh_)

#### Reason:
- cannot be empty
- check as an enum against known values

#### Explanation:
- cannot be empty
- cannot be more than {150 words | 1500 characters}

In addition to all this, we should automatically trim whitespace on all inputs. There is no case in which leading / trailing whitespace is significant that I can think of.

Feel free to weigh in, @emanelfy, @zakkain.

**Comment by zakkain** [comment]
**Full name**
`We're expecting a name that's shorter than 20 words. Please use the name recorded on your application.`

**Email** 
`Please make sure you provide a valid email address. For example, yourname@domain.com`
☝️  Thoughts on providing an example, @emanelfy ? One the one hand, I think it's good to offer an example, if it's generic enough to not seem restricting, but also illustrative of what emails are like.

**PFN**
`We're expecting a number with a different format. Please make sure this is your correct Paper File Number.`

**Reason**
@pcraig3 what does `check as an enum against known values` mean? What kind of error would we send back, aside from the "empty" error?

**Explanation**
`Sorry, there's a limit of 150 words for this explanation. Please be concise.`

**Comment by timarney** [comment]
@zakkain For reason the "enum" I have it setup to look for know values i.e. travel, medical etc... given a regular use case of someone just submitting via the form we'll always get a match.

**Comment by zakkain** [comment]
Ah, OK. So we don't need a message for that case? How would someone end up in that error state... trying to CRUD/push to our app programatically, somehow?

**Comment by timarney** [comment]
Correct - programatically submitting or messing with the form values (via dev tools etc...)

**Comment by zakkain** [comment]
OK
**Reason**
`We're expecting a reason from the list provided. Please pick one.`

Just in case ;)

**Comment by emanelfy** [comment]
@zakkain providing an example for the email is good!

However for the explanation,
_Please be concise_  -- the word **concise** doesn't have great translatability, and in terms of readability, it's considered grade 12 english which may be problematic for some. 
Could we use another word?

Also, just general question: what is our thinking around using _**Sorry**_ in some cases, and not in others?

**Comment by zakkain** [comment]
^ I'm keeping "sorry" in our back pocket to use for 2 reasons:
- when we're actually sorry (like the something went wrong page)
- when it makes the error message legitimately less harsh and accusatory

So in this example, "We're expecting a reason from the list provided" is  tonally pretty harsh. Added a "sorry" to target that  specifically. It's not included in the others as part of the pattern because they are already our fault - _we're_ expecting this input, please make sure you match that.  

Great call on "concise" – you're totally right! `Please shorten your explanation" is much simpler and translates well.

**Comment by emanelfy** [comment]
Awesome, everything looks great @zakkain!

The only other thing I wanted to flag was the word _expecting_ -- it's also a pretty challenging word for translation and readability, positioned at a post-grad level. Is there another word(s) we can use? 

Or, arguably, do we even need to say that at all? Could we just jump straight into "needs to be shorter than 20 words" or "number with a different format" etc?

**Comment by zakkain** [comment]
(Grade level shouldn't be an issue, see my comment in slack)

Good call on the translation of "expect" - works OK for Korea, not as great for Chinese (Simplified). 
You're right. "This needs to be" is better than "We're expecting", much simpler.

 cc @timarney please replace  that in the Full Name and PFN error messages 🙇 💯

**Comment by timarney** [comment]
Closing as this was merged https://github.com/cds-snc/ircc-rescheduler/pull/241
