### ISSUE TITLE
Prime users to expect that they'll be selecting days on a calendar later in the process. 

### ISSUE THREAD

**Issue by zakkain** [cds-snc/ircc-rescheduler#270]
Trello card: https://trello.com/c/oZQPDXAc/239-prime-users-to-expect-that-theyll-be-selecting-days-on-a-calendar-later-in-the-process-landing-page

This design update addresses issues raised in content testing: that user expectations of interactions later in the flow aren't properly met and primed on the landing page. 

**BEFORE:**
![image](https://user-images.githubusercontent.com/546495/42890839-d2c641c6-8a7b-11e8-8cac-a5ca31434c88.png)

**AFTER:**
![image](https://user-images.githubusercontent.com/546495/42893874-792371cc-8a83-11e8-8c87-7f76d13e7161.png)

**Changes:**
- Slight change to the relevant copy: 
> Then you’ll select **3 days** you're available between MONTH and MONTH.

cc @anikbrazeau - please drop in the French translation in a comment below :) 

- Adding an icon before the line of text below the bulleted "You will need" list - effectively turning that body text into a new "Icon and text" component. 

Layout and text indenting is similar to the "warning" component, and the icon is the same width as the yellow exclamation icon. Text size remains the same as body type, however—not reduced. 

**SVG Icon:** 
[icon_calendar.svg.zip](https://github.com/cds-snc/ircc-rescheduler/files/2206200/icon_calendar.svg.zip)

**Note:** This change is only meant to be deployed to **STAGING** for usability testing on Thursday July 19th. The icon we are using is not final, and should this design go _live_ we would need to purchase a license from [The Noun Project](https://thenounproject.com/search/?q=calendar&i=1746220) for use.

**Comment by zakkain** [comment]
Update: we're working on a better icon

**Comment by anikbrazeau** [comment]
Ensuite, vous utiliserez un calendrier pour choisir 3 jours entre _MONTH_ et _MONTH_ où vous serez disponible pour vous présenter à un rendez-vous.

**Comment by pcraig3** [comment]
The original icon is creative commons licensed, so we would just need to give credit to the creator (ie, a code comment describing where it came from or something).

👇 

![image](https://user-images.githubusercontent.com/2454380/42916680-7c68889e-8ad4-11e8-9637-0c36244f195e.png)

**Comment by pcraig3** [comment]
Done since #275 went in.
