### ISSUE TITLE
Content Update: Clarify IRCC contact schedule/parameters on the confirmation page

### ISSUE THREAD

**Issue by zakkain** [cds-snc/ircc-rescheduler#282]
This issue addresses 2 interventions from content testing:

> Users think there is a possibility that IRCC will contact them for more information close to the final contact date.
> Users worry that IRCC will contact them for more information 90 days from now and they will have to scramble or go through the whole process again.

> Users worry that the final contact date is past one the dates that they select.
> Users worry about how much notice they will receive, or if they will receive their notices after the dates of their test.

**Before:** `By [DATE], your local IRCC office will send you a new appointment, or email you to ask for more information.`

**After:** `By [DATE], we'll send you a new appointment. You will always be contacted at least 3 weeks before your appointment.`

Note: Decision to remove mention of the "we'll might ask you for more information" was based on the likelihood of that happening (in practice, it's uncommon, and _increasingly so_). It also contributes to the confusion in insight 1 - that IRCC may contact clients for more information very late in the waiting period, and require clients to choose dates again. 

cc @anikbrazeau for French translation

**Comment by zakkain** [comment]
@pcraig3 OK so we're ready to move ahead with this. Just for some context, we want to do some testing of 2 versions of this: With, and Without, the "By date" bit. Let's chat more about how that's going to work with Hillary.

**Comment by pcraig3** [comment]
This issue has been resolved since #309 and #317 went in.
