### ISSUE TITLE
Landing page: reinforce that IRCC will be picking 1 of the 3 selected days

### ISSUE THREAD

**Issue by zakkain** [cds-snc/ircc-rescheduler#314]
Trello card: https://trello.com/c/xsW2GaXf/263-landing-page-reinforce-that-ircc-will-be-picking-1-of-the-3-selected-days

This issue adds copy to the landing page explaining the back-office side of the rescheduling process for users, so they know what to expect. 

**Changes:**

- Add a new line under the calendar icon component:
![image](https://user-images.githubusercontent.com/546495/43540090-bcea30e6-9594-11e8-8602-ab32e68e725b.png)

Copy: `Then we'll review your request and send you a new appointment for one of the days you selected.`

Copy has been tested in Hemingway and Google Translate for reading level and translatability. cc @anikbrazeau for French translation

- Slight change to the copy of the calendar component:
![image](https://user-images.githubusercontent.com/546495/43540053-a498a144-9594-11e8-9ffb-1adff76e38b5.png)
Copy change from `Then` to `Next` to avoid duplicate structure line to line. cc @anikbrazeau for a slight translation change here.

**Comment by anikbrazeau** [comment]
**EN:** Then we'll review your request and send you a new appointment for one of the days you selected.

**FR:** Puis, nous examinerons votre demande et nous vous enverrons un nouveau rendez-vous pour l'un des jours que vous avez sélectionnés.

**Comment by nmakuch** [comment]
Closing this issue. This was addressed in [PR #325](https://github.com/cds-snc/ircc-rescheduler/pull/325)
