### ISSUE TITLE
Calendar page: Interaction Design cues

### ISSUE THREAD

**Issue by emanelfy** [cds-snc/ircc-rescheduler#323]
During our next round of usability testing on August 9th, we'll be testing two versions of the calendar.

Which means, we'll need two separate flows set up:

1. Your 3 selected days
vs
2. Your selected day, select 2 more

On the version of the calendar where we have "Your selected day, select 2 more" we'll need to:
- Animate the chevrons _(according to the nudge movement)_ on the calendar (both right/left directions)
- If a user is trying to select more than 3 dates, black circles for removing dates turn red (these circles are only red when the error is present on screen)

[cc @nmakuch @pcraig3]

**Comment by emanelfy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Calendar page: interaction design cues](https://trello.com/c/n6vhPn3t/281-calendar-page-interaction-design-cues)

**Comment by nmakuch** [comment]
Closing this as this has been merged in, in [Pull Request 341](https://github.com/cds-snc/ircc-rescheduler/pull/341). We have decided to go with Version B after getting feedback from our Usability Testing last Thursday
