### ISSUE TITLE
Error message copy for form and calendar pages

### ISSUE THREAD

**Issue by zakkain** [cds-snc/ircc-rescheduler#33]
# IRCC Rescheduler Error Messages

## Form page

**Full name**
- empty: “You need to tell us your full name so we can confirm your identity.”

**Paper file number**
- empty: “You need to tell us your paper file number so we can confirm your identity.”

**Reason for rescheduling**
- unselected: “Please tell us why you need to reschedule your test. If none of the options fit your situation, choose ‘Other’. 

**Briefly explain…** 
- empty: “Please tell us a bit more about why you need to reschedule your test.”

## Calendar page

Fewer than 4 dates picked on the calendar: “Please pick at least four dates so we can schedule your test when it’s convenient for you.”

**Comment by pcraig3** [comment]
The validation messages for the registration page have all been brought into the app (specifically, [in this commit](https://github.com/cds-snc/ircc-rescheduler/commit/a3ed6cb5ee0c25358402e1e1c253ff8bf9094faf)).

The calendar element is a pretty different thing altogether; probably that'll take a day or two to get working.

**Comment by pcraig3** [comment]
All of these are in since #83 went in earlier today.
