### ISSUE TITLE
Free-text inputs do not preserve line break formatting on review page

### ISSUE THREAD

**Issue by hillaryl** [cds-snc/ircc-rescheduler#424]
Sample input on register page:
<img width="632" alt="screen shot 2018-09-05 at 5 24 14 pm" src="https://user-images.githubusercontent.com/41651590/45122004-acc5f080-b130-11e8-94b5-89d7be1196a1.png">

Review page:
<img width="865" alt="screen shot 2018-09-05 at 5 24 05 pm" src="https://user-images.githubusercontent.com/41651590/45122034-bcddd000-b130-11e8-9ae3-d76b5d3f97bd.png">

**Comment by timarney** [comment]
@pcraig3 looks like white-space: pre-line would be a quick fix.

https://developer.mozilla.org/en-US/docs/Web/CSS/white-space
<img width="663" alt="screen shot 2018-09-06 at 9 13 28 am" src="https://user-images.githubusercontent.com/62242/45159674-7088a380-b1b5-11e8-8fa3-518f8365f302.png">

**Comment by nmakuch** [comment]
This was closed in [PR 457](https://github.com/cds-snc/ircc-rescheduler/pull/457)
