### ISSUE TITLE
Formatting and email treatment of plaintext family members field

### ISSUE THREAD

**Issue by zakkain** [cds-snc/ircc-rescheduler#443]
https://github.com/cds-snc/ircc-rescheduler/blob/a13d81a819f2cf503870a13349bb2f352a784b58/web/email_templates/applicant-rich.html#L43-L44

- Discussed the issues around making opinionated formatting decisions with Paul. Some solutions I recommend:

![image](https://user-images.githubusercontent.com/546495/45492471-68db7880-b73a-11e8-924d-723359ac9d35.png)

1. Change `Example:` to `For example:`
2. Put the quotation marks around `Full Name, Full Name, Full Name` but exclude `For example:` The "example" isn't quoted, only the names are.
3. Same changes apply for French.

For the email, I think we _have_ to remain un-opinionated about text in that field, and keep that formatting in the email. Sure, some people might get really long, messy emails, but that might actually look "correct" because that formatting is how they input their text. This is something to observe, IMO, and if folks are putting descriptive info in that field, we can modify the description/instruction copy to either accommodate that, or specifically recommend against it.

**Comment by timarney** [comment]
Casting a vote for "For example:"

**Comment by pcraig3** [comment]
@timarney, here, I'll update the placeholder text as per Zak's revisions.

**Comment by pcraig3** [comment]
@timarney,

The other point here is whether to change the names in the email message, which @zakkain says to leave it be.

Unfortunately, I'm still getting this in my emails:

### staff email
![image](https://user-images.githubusercontent.com/2454380/45648496-c05d4980-ba96-11e8-9460-d56484401b4d.png)

### user email
![image](https://user-images.githubusercontent.com/2454380/45648567-ebe03400-ba96-11e8-9efd-90ec0f2ec6f8.png)

I think it would be a nice quality of life thing to prepend the family option string (if it exists) with `, `. 

Thoughts?

**Comment by timarney** [comment]
I think that would be a nice touch easy enough to setup.
