### ISSUE TITLE
Experiment with colours to establish higher contrast on form + calendar page.

### ISSUE THREAD

**Issue by timarney** [cds-snc/ircc-rescheduler#446]
Based on feedback from usability testing:

- Users don't see the field for the family option when checking the box, only on second page load after triggering an error (on a zoomed in and inverted screen).
- Calendar icon doesn't appear on inverted screen
- Inverted Screen: there isn't any contrast between available and unavailable dates.
- (Inverted color display) Family field not visible until an error is triggered.
- User cannot distinguish between available days and unavailable days due to lack of contrast.
- User expected that unavailable days would have been blacked out completely.
- Knowing that tuesday and wednesday were available was not helpful because those days earlier in the month were unavailable.

Note: @emanelfy added a new label "design needed" in an effort to clarify where we need direction.

**Comment by emanelfy** [comment]
With the new green colour we've added to the calendar (as well as the new hover states and disabled dates icon) this should address all the issues with contrast. 

The remaining things on the list are all assistive-device specific and require further investigation.

**Comment by timarney** [comment]
🎉 merged.
