### ISSUE TITLE
Error Page Copy (500, 404)

### ISSUE THREAD

**Issue by zakkain** [cds-snc/ircc-rescheduler#449]
From this Trello card: https://trello.com/c/I4Troh1N/360-review-copy-on-the-various-error-pages

## 500 - Server Error
Page title/h1: `Something went wrong`
Body (formatted like the `Error` page): `Please refresh the page, or try the link in your email or letter again. If you keep seeing this page, please contact IRCC directly to reschedule your appointment:` [include call centre number and webform URL in the format of the confirmation page] 

**-> UPDATED Friday, 12:15pm**

cc @timarney is that the right course of action someone should take if they hit a 500 error? Feedback welcome.

## 404 Error
Looks good to me, but remove the second body text line and add a "< Go back" link to that page. How can we do that cleanly with awareness of our subdomains? 

Hmm, OK with the global 404 page then, we should do something like this:
`The page you're trying to reach doesn't exist. Please try again, and double-check the link in your email or letter.`

**Comment by zakkain** [comment]
@timarney @emanelfy thoughts? Edited original post based on feedback

**Comment by timarney** [comment]
https://github.com/cds-snc/ircc-rescheduler/pull/467 🎉
