### ISSUE TITLE
Read "unavailable" as the first thing ahead of a date instead of the last.

### ISSUE THREAD

**Issue by timarney** [cds-snc/ircc-rescheduler#450]
Screen readers have to go through every unavailable date before landing on an available date.

User has to listen to the full date for the word "dimmed" before moving to the next. Tedious to find available date.

Not clear when an interaction will be possible or if it's possible.

(JAWS) Whether dates are tagged as "unavailable" or have no description changes depending on what other interactions have taken place

**Comment by timarney** [comment]
Work in progress ...

@zakkain I have an english version of this in progress. The label now reads "unavailable Tuesday, October 2, 2018".  Voice over adds "dimmed" at the end.

<img width="533" alt="screen shot 2018-09-13 at 4 23 42 pm" src="https://user-images.githubusercontent.com/62242/45513808-b8896680-b771-11e8-8450-d77fda66bb49.png">

Comments?

**Comment by timarney** [comment]
PR here https://github.com/cds-snc/ircc-rescheduler/pull/451

**Comment by zakkain** [comment]
👍
