### ISSUE TITLE
Usability Testing: Unavailability Flow 

### ISSUE THREAD

**Issue by hillaryl** [cds-snc/ircc-rescheduler#452]
### **1. Content Updates** @timarney @pcraig3 @nmakuch @zakkain @anikbrazeau 
https://github.com/cds-snc/ircc-rescheduler/issues/398#issuecomment-418880887

###**Unavailability Flow Explanation page**
**Page title** 👉 Apply for an appointment extension

 **Page description text** 👉 If you cannot attend an appointment on any of the available days, staff may not be able to accommodate your request to reschedule. [Line about policy, checking with an IRCC local office — Our policy is to delay appointments a maximum of two months, unless ____ reason.]
We’ll review your request and determine if we can accommodate your unavailability and get back to you within 1 week.

** Box label** 👉 When are you unavailable?

** Box description** 👉 If you haven’t already, please provide a reason for your unavailability.

 **Empty box error** 👉 Please provide us with more information.

+French Translation 

### **Unavailability flow review page**
@zakkain to supply error message for if a user tries to continue without entering text in the field, and a warning box message to clarify that their request may be reviewed and that they should attend their original appointment, and when staff will respond to users by.

This also changes the nature of the warning messages from that point forward in the flow (review page, etc).

### **Unavailability Flow Confirmation Page**
@zakkain to copy changes specific to this flow

### **Design Updates** @timarney @nmakuch @pcraig3 
https://github.com/cds-snc/ircc-rescheduler/issues/398#issuecomment-418899429

Remove "these dates don't work for me" link and insert a check box instead:
<img width="881" alt="45123855-43e17700-b136-11e8-89e7-90dc4d2c4156" src="https://user-images.githubusercontent.com/41651590/45556180-a4447880-b808-11e8-8d83-9bf6048873a0.png">

When the box is checked, the calendar should change to grey and become inactive.
The green button at the bottom of the page should change to say next (in all cases) and take users to the explanation page.

**Other interaction design elements on the calendar page to be added:**

Arrow on the calendar will be green (colour to match our buttons) and jiggle (only on the first page of the calendar)

the highlight colour on the calendar is now a lighter shade of green instead of grey

the icon that appears on the non-selectable dates should be red (to match our error messaging)

### **Explanation page update:**
Include "< Go back" link at the top of the page.
[see previous comment above for copy edits]

### **3. Updated Sample BELA Letter, BELA email content and Confirmation Email** @zakkain 
- French and English

_See Trello for test event details_

**Comment by hillaryl** [comment]
@emanelfy @pcraig3 We had discussed a separate review and confirmation page for the unavailability flow, so that users in this flow do not see the "do not attend your original appointment warning." Is this documented anywhere?

**Comment by zakkain** [comment]
Updates Sample BELA letters (EN/FR) are uploaded to [Gdrive](https://drive.google.com/drive/folders/1etQRqBd_UXjAgMMH5yq7KNr-Ys0V6lI2)

Confirmation email for Extension use case: [link](https://docs.google.com/document/d/1XCm3oDvzR-aNZE6Q_WFwKxNTaAIbdXPjRXpmtBRnMPg/edit)

**Comment by timarney** [comment]
The WIP PR is here https://github.com/cds-snc/ircc-rescheduler/pull/438

Current preview link https://ircc-development-pr-438.herokuapp.com/calendar

**Comment by kyliehavelock** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement a user flow for when applicants have extended unavailability](https://trello.com/c/mjSMMSBb/317-implement-a-user-flow-for-when-applicants-have-extended-unavailability)

**Comment by timarney** [comment]
Based on the updated [email template](https://docs.google.com/document/d/1XCm3oDvzR-aNZE6Q_WFwKxNTaAIbdXPjRXpmtBRnMPg/edit) for the "Unavailability Flow" we're dropping output of the family option fields.

```
Individuals to be rescheduled:
Full name,  [family option]
```
Before I make that update does anyone think there's a need to keep that in the new template?

cc: @hillaryl @kyliehavelock

**Comment by hillaryl** [comment]
If the client is saying that both they and their family members are unavailable for an extended period of time I think that would be useful for office staff to know. The calendar page they're coming from still says "Select 3 days you and your family are available..." so the user will be expecting that they are sending it on everyone's behalf. We can make sure that this is the case in testing. @emanelfy what do you think?

**Comment by hillaryl** [comment]
@zakkain @emanelfy

**Comment by hillaryl** [comment]
@zakkain @emanelfy 
Suggested copy for the unavailability flow confirmation page:

> IRCC will review your request and get back to you within 1 week.

**Comment by emanelfy** [comment]
On the calendar page, if a user checks the box "I cannot attend any of the available appointments" the warning box message should be **_hidden_**. 

--
cc @timarney @pcraig3

**Comment by emanelfy** [comment]
**In terms of updated content for the explanation page:**

_[same]_ If you cannot attend an appointment on any of the available days, staff may not be able to accommodate your request to reschedule.

_[same]_ Our policy is to delay appointments a maximum of two months. We’ll review your request and determine if we can accommodate your unavailability and get back to you within 1 week.

_[new]_ When are you unavailable?
_**If you haven’t already, please provide the exact dates and reason for your unavailability.**_

--
cc @timarney @pcraig3 @zakkain

**Comment by timarney** [comment]
> On the calendar page, if a user checks the box "I cannot attend any of the available appointments" the warning box message should be hidden.

https://github.com/cds-snc/ircc-rescheduler/pull/478 (merged)

> If you haven’t already, please provide the exact dates and reason for your unavailability.

https://github.com/cds-snc/ircc-rescheduler/pull/483 (coming soon)

NoJS flow for this - https://github.com/cds-snc/ircc-rescheduler/pull/476 (coming soon) @pcraig3 is looking at one more issue on this.

**Comment by pcraig3** [comment]
Closing this issue since #476 went in.
