### ISSUE TITLE
Get HTTPS

### ISSUE THREAD

**Issue by pcraig3** [cds-snc/ircc-rescheduler#6]
We are all about dat ![image](https://user-images.githubusercontent.com/2454380/38285798-f1948db8-378f-11e8-88cf-16fc41f3e4e4.png) hashtag ![image](https://user-images.githubusercontent.com/2454380/38285798-f1948db8-378f-11e8-88cf-16fc41f3e4e4.png) green ![image](https://user-images.githubusercontent.com/2454380/38285798-f1948db8-378f-11e8-88cf-16fc41f3e4e4.png) padlock ![image](https://user-images.githubusercontent.com/2454380/38285798-f1948db8-378f-11e8-88cf-16fc41f3e4e4.png) life ![image](https://user-images.githubusercontent.com/2454380/38285798-f1948db8-378f-11e8-88cf-16fc41f3e4e4.png) here at CDS.

**Comment by sleepycat** [comment]
![ssl](https://user-images.githubusercontent.com/109692/39845851-3a556200-53c6-11e8-8c3e-f42a023337ec.png)
