### ISSUE TITLE
Calendar page error state

### ISSUE THREAD

**Issue by zakkain** [cds-snc/ircc-rescheduler#79]
There should only be one error surfaced to users, that cover the different error states

`Please select three (3) dates, so we can schedule an appointment when you are available.`

That will apply to both the "they didn't choose any dates" and the "they chose less than 3 dates" cases. Let's not fire an error when they try to select _more_ - the selection just won't take place (clicking the calendar won't do anything, fail silently). Given what we saw in usability testing nobody tried to select more so I don't think, at this stage, we need an error state to specifically address that

**Comment by pcraig3** [comment]
👍 okay, cool. 

It should me more obvious once the different days are showing up in the margin as well.

**Comment by pcraig3** [comment]
Pull request #83 adds this in.

**Comment by pcraig3** [comment]
This is in now.
