### ISSUE TITLE
Parse selected dates and style date list items in `/calendar` 🗓

### ISSUE THREAD

**Issue by chowdhurian** [cds-snc/ircc-rescheduler#86]
The new design includes adding dates to the screen as they're clicked. Currently the selected dates are displayed in an unstyled list and as a stringified Date object.

Todo:
* parse the date into a more human-readable form
* style the list

Current:
<img width="399" alt="screen shot 2018-05-01 at 17 22 29" src="https://user-images.githubusercontent.com/10335475/39499665-455b7daa-4d64-11e8-85ac-80e2023c9ee0.png">

**Comment by pcraig3** [comment]
Hiya, the design is being iterated still so there's no 'final' version that we have around. But here's a recent tweet that gives an idea what direction we're moving in. 

https://twitter.com/CDS_GC/status/989245581963988993

But yes, your two bullet points are correct, and I'll update this as we go.

**Comment by pcraig3** [comment]
Hey @chowdhurian, [I've created a project for the calendar](https://github.com/cds-snc/ircc-rescheduler/projects/1) which might be a more proactive way to go about showing our work.

If you raise any more calendar-related issues (and feel free to!), I'll stick them in the project so that progress on them is visible.

**Comment by chowdhurian** [comment]
That's an interesting coincidence, @pcraig3. In a project discussion yesterday, we touched on using Github's Project feature but stayed with Trello because none of us had used it before. But Trello feels more closed, so I'll use this as an evaluation of how the feature lends itself to open source work.
