### ISSUE TITLE
Improve form validation errors on registration page

### ISSUE THREAD

**Issue by pcraig3** [cds-snc/ircc-rescheduler#92]
**Note** 
Some work has been done on this. [See final comment](https://github.com/cds-snc/ircc-rescheduler/issues/92#issuecomment-391388702).

***

# Problems

There are several usability problems that have been highlighted over a couple rounds of user research concerning our registration form -- specifically around how errors are being shown (or not shown) to users.

## 1. users don't see inline validation errors

Our inline validation errors (that is, errors that appear immediately after the form input loses focus) are being missed by users. The proposed fix for this is to hold off on field validation until the user clicks "Next →".

**Solution: Wait until the user clicks the submit button to validate their inputs.** 

## 2. submit button is disabled unless all fields are valid

Several users have ended up trying to click the submit button but not being able to because of an error further up the page. When errors show up, they are sometimes not aware of them and then confused why they can't click the  button.

**Solution: The button should always be enabled. Users can click it at any point.**

## 3. validation errors aren't being highlighted to users

Currently, when errors appear on the page we are not making users aware of them. This is particularly the case with non-visual interfaces (such as screenreaders). 
A good solution to this is the following:
- validate errors when users click the submit button
- if errors are found, create a component at the top of the page that lists all errors ([here is an example](http://alphagov.github.io/digitalmarketplace-frontend-toolkit/forms/validation.html))
  - error-list component should have a generic header
  - error-list component should list fields with errors and then anchor link to them (ie `<a href="#fullName">`)
  - error-list component should be programatically focused as soon as it appears

An example of this interaction pattern can be found [on the Digital Marketplace](https://www.digitalmarketplace.service.gov.uk/suppliers/create/duns-number). To test it out, enter something in the field that isn't a number and then click "Save and continue".

**Solution: create an error=list component that receives focus, and then lists and links to errors on the page.**

## 4. `<header>` elements are not allowed inside `<label>` elements

[`<label>` elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label) can only accept [phrasing content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content). So we should change the markup for our form labels on the registration page. I would suggest a `<span>` with an appropriate classname. I get that it's not very component-y, but it will solve this problem for us and then we can revisit it later.

# Progress

- [x] users don't see inline validation errors
- [x] submit button is disabled unless all fields are valid
- [x] validation errors aren't being highlighted to users
- [x] `<header>` elements are not allowed inside `<label>` elements

**Comment by Amirroracle** [comment]
>1. users don't see inline validation errors
when the user clicks 'submit' or 'next' and a form error occurs, will there be a focus on the exact element that fails validation, and if there are several validation failures, which one should we focus on (maybe the top one?). 

>2. submit button is disabled unless all fields are valid
I agree, the button should just be always enabled.

>3. validation errors aren't being highlighted to users
Looks like you addressed my issue from point 1 in this, I think it's a good idea to group errors into one component at the top of the page, only issue is styling and design. It's a widely used practice and I'm for it. What some people do is that they have inline client-side form validation and server-side onSubmit validation (which would group errors at the top). Though I do wonder what accessibility concerns arise from error components, is it better to create it on load and leave it hidden until the form reaches an error state or should we create it if the form reaches an error state? I wonder if this poses an issue with screen-readers parsing html, is that kind of error state accessible? 

>4. <header> elements are not allowed inside <label> elements
This ties into the HTML validation errors I suppose.

**Comment by pcraig3** [comment]
> when the user clicks 'submit' or 'next' and a form error occurs, will there be a focus on the exact element that fails validation, and if there are several validation failures, which one should we focus on (maybe the top one?).

Addressed by (3). Focus an element at the top of the page.

> I agree, the button should just be always enabled.

👍 

> Though I do wonder what accessibility concerns arise from error components, is it better to create it on load and leave it hidden until the form reaches an error state or should we create it if the form reaches an error state? 

It looks like we should create an empty error-list container and then fill it up with HTML when needed (rather than hiding/unhiding). [Here's the recommendation to do that](https://www.w3.org/TR/WCAG20-TECHS/ARIA19.html#ARIA19-procedure).

> I wonder if this poses an issue with screen-readers parsing html, is that kind of error state accessible?

When new stuff appears on the screen,  [you can use aria role="alert"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role) to announce to screenreaders that something new has appeared that they should look at. 

Also, forcing the focus up there is a pretty strong signal.

**Comment by pcraig3** [comment]
@nmakuch got this in -> https://github.com/cds-snc/ircc-rescheduler/pull/120

🎉
